package io.migrax.cli;

import io.migrax.dialect.Dialect;
import io.migrax.diff.Migrations;
import io.migrax.model.SchemaModel;
import io.migrax.ops.AddColumn;
import io.migrax.ops.AlterColumn;
import io.migrax.ops.CreateTable;
import io.migrax.ops.DropColumn;
import io.migrax.ops.DropTable;
import io.migrax.ops.Operation;
import io.migrax.runner.MigrationLoader;
import java.nio.file.Files;
import java.nio.file.Path;
import java.util.List;

/** Writes operations as migration SQL and rollback scripts. */
final class MigrationSql {
  private MigrationSql() {}

  /**
   * A migration file's SQL for the changes from {@code before} to {@code after}, prepared for
   * the database first ({@link Dialect#prepare}: SQLite rebuilds tables).
   */
  static String render(Dialect dialect, List<Operation> operations, String header,
                       SchemaModel before, SchemaModel after) {
    return render(dialect, dialect.prepare(operations, before, after), header);
  }

  /** A migration file's SQL: the "Generated by" line, an optional header, the statements. */
  static String render(Dialect dialect, List<Operation> operations, String header) {
    StringBuilder sql = new StringBuilder("-- Generated by Migrax ").append(Version.current())
        .append(" for ").append(dialect.id()).append("\n");
    if (header != null) {
      sql.append(header);
    }
    sql.append("\n");
    for (Operation operation : operations) {
      sql.append(dialect.render(operation)).append(";\n");
    }
    return sql.toString();
  }

  /** Writes rollback/<fileName>, with warnings about data the rollback cannot restore. */
  static void writeRollback(Path migrations, String fileName, Dialect dialect,
                            List<Operation> reverse, List<Operation> forward,
                            SchemaModel before, SchemaModel after)
      throws Exception {
    Path folder = migrations.resolve(MigrationLoader.ROLLBACK_FOLDER);
    Files.createDirectories(folder);
    StringBuilder header = new StringBuilder("-- Rollback for ").append(fileName)
        .append(". 'migrax rollback' runs it.\n");
    for (Operation operation : forward) {
      String subject = Migrations.summary(operation).replaceFirst("^\\S+ \\S+ ", "");
      if (operation instanceof DropColumn || operation instanceof DropTable
          || operation instanceof AlterColumn alter && alter.destructive()) {
        header.append("-- WARNING: restores the structure of ").append(subject)
            .append(" but not its data.\n");
      } else if (operation instanceof AddColumn || operation instanceof CreateTable) {
        header.append("-- Note: deletes data written to ").append(subject)
            .append(" since the migration ran.\n");
      }
    }
    String sql = reverse.isEmpty()
        ? "-- Generated by Migrax " + Version.current() + " for " + dialect.id() + "\n" + header
            + "-- Nothing to undo.\n"
        : render(dialect, reverse, header.toString(), before, after);
    Files.writeString(folder.resolve(fileName), sql);
  }
}
