package io.migrax.dialect;

import io.migrax.model.SchemaModel;
import io.migrax.ops.*;
import java.util.List;
import java.util.stream.Collectors;

public abstract class AbstractDialect implements Dialect {
    @Override public String render(Operation o) {
        if (o instanceof CreateSequence x) return createSequence(x.sequence());
        if (o instanceof DropSequence x) return dropSequence(x.name());
        if (o instanceof CreateTable x) return createTable(x.table());
        if (o instanceof DropTable x) return "DROP TABLE " + q(x.table());
        if (o instanceof AddColumn x) return addColumn(x.table(), x.column());
        if (o instanceof DropColumn x) return "ALTER TABLE " + q(x.table()) + " DROP COLUMN " + q(x.column());
        if (o instanceof RenameColumn x) return renameColumn(x.table(), x.from(), x.to());
        if (o instanceof AlterColumn x) return alterColumn(x.table(), x.before(), x.after());
        if (o instanceof AddPrimaryKey x) return addPrimaryKey(x.table(), x.key());
        if (o instanceof DropPrimaryKey x) return dropPrimaryKey(x.table(), x.constraintName());
        if (o instanceof AddIndex x) return "CREATE " + (x.index().unique() ? "UNIQUE " : "") + "INDEX " + q(x.index().name()) + " ON " + q(x.table()) + " (" + join(x.index().columns()) + ")";
        if (o instanceof DropIndex x) return dropIndex(x.table(), x.name());
        if (o instanceof AddForeignKey x) return "ALTER TABLE " + q(x.table()) + " ADD CONSTRAINT " + q(x.fk().name()) + " FOREIGN KEY (" + join(x.fk().columns()) + ") REFERENCES " + q(x.fk().referencedTable()) + " (" + join(x.fk().referencedColumns()) + ")";
        if (o instanceof DropForeignKey x) return dropForeignKey(x.table(), x.name());
        if (o instanceof RunSql x) return x.sql();
        throw new IllegalArgumentException("Unsupported operation " + o);
    }

    protected String createTable(SchemaModel.Table t) {
        String cols = t.columns().stream().map(this::column).collect(Collectors.joining(", "));
        String pk = t.primaryKey() == null ? "" : ", CONSTRAINT "
            + q(t.primaryKey().constraintName() == null || t.primaryKey().constraintName().isBlank()
                ? SchemaModel.primaryKeyConstraintName(t.name())
                : t.primaryKey().constraintName())
            + " PRIMARY KEY (" + join(t.primaryKey().columns()) + ")";
        return "CREATE TABLE " + q(t.name()) + " (" + cols + pk + ")";
    }
    protected String addColumn(String table, SchemaModel.Column column) {
        return "ALTER TABLE " + q(table) + " ADD COLUMN " + column(column);
    }
    protected String addPrimaryKey(String table, SchemaModel.PrimaryKey key) {
        String name = key.constraintName() == null || key.constraintName().isBlank()
            ? SchemaModel.primaryKeyConstraintName(table)
            : key.constraintName();
        return "ALTER TABLE " + q(table) + " ADD CONSTRAINT " + q(name)
            + " PRIMARY KEY (" + join(key.columns()) + ")";
    }
    protected String alterColumn(String table, SchemaModel.Column before, SchemaModel.Column after) {
        return "ALTER TABLE " + q(table) + " ALTER COLUMN " + q(after.name()) + " TYPE " + renderType(after);
    }
    protected String renameColumn(String table, String from, String to) {
        return "ALTER TABLE " + q(table) + " RENAME COLUMN " + q(from) + " TO " + q(to);
    }
    protected String dropPrimaryKey(String table, String constraintName) {
        if (constraintName == null || constraintName.isBlank()) {
            throw new IllegalStateException(
                "Cannot drop the primary key on '" + table
                    + "' because its constraint name is unavailable in the schema snapshot.");
        }
        return "ALTER TABLE " + q(table) + " DROP CONSTRAINT " + q(constraintName);
    }
    protected String dropForeignKey(String table, String name) {
        return "ALTER TABLE " + q(table) + " DROP CONSTRAINT " + q(name);
    }
    protected String dropIndex(String table, String name) { return "DROP INDEX " + q(name); }
    protected String column(SchemaModel.Column c) {
        String type=renderType(c);
        if(c.identity()) type=identityType(c);
        String d=c.defaultValue()!=null ? " DEFAULT "+c.defaultValue() : (c.sequenceName()!=null ? " DEFAULT "+sequenceDefault(c.sequenceName()) : "");
        return q(c.name())+" "+type+(c.nullable()?"":" NOT NULL")+d+(c.unique()?" UNIQUE":"");
    }
    protected String identityType(SchemaModel.Column c){return c.sqlType()+" GENERATED BY DEFAULT AS IDENTITY";}
    protected String renderType(SchemaModel.Column c){return c.sqlType()!=null&&!c.sqlType().equalsIgnoreCase(c.logicalType())?c.sqlType():c.sqlType();}
    protected String sequenceDefault(String name){return "nextval('"+name+"')";}
    protected String createSequence(SchemaModel.Sequence s){return "CREATE SEQUENCE "+q(s.name())+" START WITH "+s.initialValue()+" INCREMENT BY "+s.allocationSize();}
    protected String dropSequence(String name){return "DROP SEQUENCE "+q(name);}
    protected String join(List<String> values) { return values.stream().map(this::q).collect(Collectors.joining(", ")); }
    protected String q(String identifier) { return quote(identifier); }
}
