package io.migrax.plugin;

import io.migrax.diff.DiffEngine;
import io.migrax.model.SchemaModel;
import io.migrax.ops.AddColumn;
import io.migrax.ops.DropPrimaryKey;
import io.migrax.dialect.PostgresDialect;
import org.junit.jupiter.api.Test;

import java.sql.DriverManager;
import java.util.List;

import static org.junit.jupiter.api.Assertions.assertEquals;
import static org.junit.jupiter.api.Assertions.assertInstanceOf;
import static org.junit.jupiter.api.Assertions.assertTrue;

class DatabaseSchemaReaderTest {
  @Test
  void readsTheSequenceBehindAColumnDefault() {
    assertEquals("customer_seq",
        DatabaseSchemaReader.defaultSequence("nextval('customer_seq'::regclass)"));
    assertEquals("Orders_SEQ",
        DatabaseSchemaReader.defaultSequence("nextval('public.\"Orders_SEQ\"'::regclass)"));
    assertEquals(null, DatabaseSchemaReader.defaultSequence("'draft'::character varying"));
    assertEquals(null, DatabaseSchemaReader.defaultSequence(null));
  }

  @Test
  void ignoresTheIndexH2CreatesForAForeignKey() throws Exception {
    try (var connection = DriverManager.getConnection("jdbc:h2:mem:foreign-key-index")) {
      try (var statement = connection.createStatement()) {
        statement.execute("CREATE TABLE customer (id BIGINT PRIMARY KEY)");
        statement.execute("CREATE TABLE orders (id BIGINT PRIMARY KEY, customer_id BIGINT, "
            + "note VARCHAR(20), CONSTRAINT fk_orders_customer_id FOREIGN KEY (customer_id) "
            + "REFERENCES customer (id))");
        statement.execute("CREATE INDEX fk_orders_note_index_1 ON orders (note)");
      }

      SchemaModel.Table orders = DatabaseSchemaReader.read(connection).table("orders");

      assertEquals(1, orders.foreignKeys().size());
      assertEquals(List.of("fk_orders_note_index_1"),
          orders.indexes().stream().map(SchemaModel.Index::name).toList(),
          "only the index H2 created for the foreign key is left out");
    }
  }

  @Test
  void readsSchemaMetadataForAnExistingDatabaseBaseline() throws Exception {
    try (var connection = DriverManager.getConnection("jdbc:h2:mem:baseline-reader")) {
      try (var statement = connection.createStatement()) {
        statement.execute("""
            CREATE TABLE existing_records (
              id BIGINT GENERATED BY DEFAULT AS IDENTITY,
              CONSTRAINT pk_existing_records PRIMARY KEY (id),
              username VARCHAR(40) NOT NULL
            )
            """);
        statement.execute("CREATE INDEX ix_existing_records_username ON existing_records(username)");
      }

      SchemaModel database = DatabaseSchemaReader.read(connection);
      SchemaModel.Table table = database.table("EXISTING_RECORDS");
      if (table == null) {
        table = database.table("existing_records");
      }

      assertTrue(table != null);
      assertEquals(List.of("id"), table.primaryKey().columns());
      assertEquals("pk_existing_records", table.primaryKey().constraintName());
      assertTrue(table.column("USERNAME") != null || table.column("username") != null);
      assertEquals(1, table.indexes().size());

      SchemaModel.Table updated = new SchemaModel.Table(
          table.name(),
          java.util.stream.Stream.concat(table.columns().stream(), java.util.stream.Stream.of(
              new SchemaModel.Column("email", "varchar", true, 255, null, null,
                  null, false, false, null, "varchar"))).toList(),
          table.primaryKey(),
          table.indexes(),
          table.foreignKeys());
      var changes = new DiffEngine().diff(database, new SchemaModel(List.of(updated)));
      assertEquals(1, changes.size());
      assertInstanceOf(AddColumn.class, changes.get(0));

      SchemaModel.Table withoutPrimaryKey = new SchemaModel.Table(
          table.name(), table.columns(), null, table.indexes(), table.foreignKeys());
      var drop = new DiffEngine().diff(database, new SchemaModel(List.of(withoutPrimaryKey))).stream()
          .filter(DropPrimaryKey.class::isInstance)
          .map(DropPrimaryKey.class::cast)
          .findFirst()
          .orElseThrow();
      assertEquals("pk_existing_records", drop.constraintName());
      assertTrue(new PostgresDialect().render(drop).contains("DROP CONSTRAINT pk_existing_records"));
    }
  }
}
