package io.migrax.util;

import io.migrax.model.SchemaModel;
import java.nio.file.*;
import java.util.*;

/** Small dependency-free JSON codec for the neutral schema snapshot. */
public final class Json {
  private Json(){}
  public static String write(SchemaModel m){
    StringBuilder b=new StringBuilder("{\n  \"tables\": [\n");
    for(int i=0;i<m.tables().size();i++){if(i>0)b.append(",\n");var t=m.tables().get(i);b.append("    {\"name\":").append(q(t.name())).append(",\"columns\":[");for(int j=0;j<t.columns().size();j++){if(j>0)b.append(',');var c=t.columns().get(j);b.append("{\"name\":").append(q(c.name())).append(",\"sqlType\":").append(q(c.sqlType())).append(",\"nullable\":").append(c.nullable()).append(",\"length\":").append(n(c.length())).append(",\"precision\":").append(n(c.precision())).append(",\"scale\":").append(n(c.scale())).append(",\"defaultValue\":").append(qn(c.defaultValue())).append(",\"unique\":").append(c.unique()).append(",\"identity\":").append(c.identity()).append(",\"sequenceName\":").append(qn(c.sequenceName())).append(",\"logicalType\":").append(q(c.logicalType())).append("}");}b.append("],\"primaryKey\":").append(pk(t.primaryKey())).append(",\"indexes\":[");for(int j=0;j<t.indexes().size();j++){if(j>0)b.append(',');var x=t.indexes().get(j);b.append("{\"name\":").append(q(x.name())).append(",\"columns\":").append(arr(x.columns())).append(",\"unique\":").append(x.unique()).append('}');}b.append("],\"foreignKeys\":[");for(int j=0;j<t.foreignKeys().size();j++){if(j>0)b.append(',');var x=t.foreignKeys().get(j);b.append("{\"name\":").append(q(x.name())).append(",\"columns\":").append(arr(x.columns())).append(",\"referencedTable\":").append(q(x.referencedTable())).append(",\"referencedColumns\":").append(arr(x.referencedColumns())).append('}');}b.append("]}");}
    b.append("\n  ],\n  \"sequences\": [");for(int i=0;i<m.sequences().size();i++){if(i>0)b.append(',');var s=m.sequences().get(i);b.append("{\"name\":").append(q(s.name())).append(",\"initialValue\":").append(s.initialValue()).append(",\"allocationSize\":").append(s.allocationSize()).append('}');}return b.append("]\n}\n").toString();
  }
  private static String q(String s){return "\""+s.replace("\\","\\\\").replace("\"","\\\"").replace("\n","\\n")+"\"";}private static String qn(String s){return s==null?"null":q(s);}private static String n(Number x){return x==null?"null":x.toString();}private static String arr(List<String>x){StringBuilder b=new StringBuilder("[");for(int i=0;i<x.size();i++){if(i>0)b.append(',');b.append(q(x.get(i)));}return b.append(']').toString();}private static String pk(SchemaModel.PrimaryKey p){return p==null?"null":"{\"columns\":"+arr(p.columns())+",\"constraintName\":"+qn(p.constraintName())+"}";}
  public static void write(Path p,SchemaModel m)throws Exception{Files.createDirectories(p.getParent());Files.writeString(p,write(m));}
  public static SchemaModel read(Path p)throws Exception{return parse(Files.readString(p));}
  public static SchemaModel parse(String s){Object v=new Parser(s).parse();Map<?,?> root=(Map<?,?>)v;List<SchemaModel.Table> ts=new ArrayList<>();for(Object to:list(root,"tables")){Map<?,?> t=(Map<?,?>)to;List<SchemaModel.Column> cs=new ArrayList<>();for(Object co:list(t,"columns")){Map<?,?> c=(Map<?,?>)co;cs.add(new SchemaModel.Column(str(c,"name"),str(c,"sqlType"),bool(c,"nullable"),integer(c,"length"),integer(c,"precision"),integer(c,"scale"),nullableStr(c,"defaultValue"),bool(c,"unique"),bool(c,"identity"),nullableStr(c,"sequenceName"),strOr(c,"logicalType",str(c,"sqlType"))));}SchemaModel.PrimaryKey pk=null;if(t.get("primaryKey") instanceof Map){Map<?,?> pkm=(Map<?,?>)t.get("primaryKey");pk=new SchemaModel.PrimaryKey(strings((List<?>)pkm.get("columns")),nullableStr(pkm,"constraintName"));}List<SchemaModel.Index> ix=new ArrayList<>();for(Object io:list(t,"indexes")){Map<?,?> x=(Map<?,?>)io;ix.add(new SchemaModel.Index(str(x,"name"),strings((List<?>)x.get("columns")),bool(x,"unique")));}List<SchemaModel.ForeignKey> fk=new ArrayList<>();for(Object fo:list(t,"foreignKeys")){Map<?,?> x=(Map<?,?>)fo;fk.add(new SchemaModel.ForeignKey(str(x,"name"),strings((List<?>)x.get("columns")),str(x,"referencedTable"),strings((List<?>)x.get("referencedColumns"))));}ts.add(new SchemaModel.Table(str(t,"name"),cs,pk,ix,fk));}List<SchemaModel.Sequence> ss=new ArrayList<>();for(Object so:list(root,"sequences")){Map<?,?> x=(Map<?,?>)so;Object iv=x.get("initialValue"),av=x.get("allocationSize");ss.add(new SchemaModel.Sequence(str(x,"name"),iv instanceof Number?((Number)iv).longValue():1,av instanceof Number?((Number)av).longValue():50));}return new SchemaModel(ts,ss);}
  static List<?> list(Map<?,?>m,String k){Object x=m.get(k);return x instanceof List?(List<?>)x:List.of();}
  static String str(Map<?,?>m,String k){Object x=m.get(k);return x==null?"":String.valueOf(x);}static String strOr(Map<?,?>m,String k,String d){Object x=m.get(k);return x==null?d:String.valueOf(x);}static String nullableStr(Map<?,?>m,String k){Object x=m.get(k);return x==null?null:String.valueOf(x);}static boolean bool(Map<?,?>m,String k){Object x=m.get(k);return Boolean.TRUE.equals(x);}static Integer integer(Map<?,?>m,String k){Object x=m.get(k);return x instanceof Number?((Number)x).intValue():null;}static List<String> strings(List<?>x){List<String>r=new ArrayList<>();for(Object o:x)r.add(String.valueOf(o));return r;}
  static final class Parser{final String s;int i;Parser(String s){this.s=s;}Object parse(){skip();return value();}Object value(){skip();char c=s.charAt(i);if(c=='{')return obj();if(c=='[')return arr();if(c=='"')return str();if(s.startsWith("true",i)){i+=4;return true;}if(s.startsWith("false",i)){i+=5;return false;}if(s.startsWith("null",i)){i+=4;return null;}int st=i;while(i<s.length()&&"-0123456789.eE".indexOf(s.charAt(i))>=0)i++;String n=s.substring(st,i);return n.contains(".")||n.contains("e")||n.contains("E")?Double.valueOf(n):Long.valueOf(n);}Map<String,Object> obj(){Map<String,Object>m=new LinkedHashMap<>();i++;skip();if(s.charAt(i)=='}'){i++;return m;}while(true){String k=str();skip();i++;m.put(k,value());skip();if(s.charAt(i)=='}'){i++;return m;}i++;skip();}}List<Object> arr(){List<Object>l=new ArrayList<>();i++;skip();if(s.charAt(i)==']'){i++;return l;}while(true){l.add(value());skip();if(s.charAt(i)==']'){i++;return l;}i++;skip();}}String str(){i++;StringBuilder b=new StringBuilder();while(i<s.length()){char c=s.charAt(i++);if(c=='"')break;if(c=='\\'){char n=s.charAt(i++);b.append(n=='n'?'\n':n=='r'?'\r':n=='t'?'\t':n);}else b.append(c);}return b.toString();}void skip(){while(i<s.length()&&Character.isWhitespace(s.charAt(i)))i++;}}
}
